[tool.poetry]
name = "trazurebot"
version = "1.0.0"
description = ""
authors = ["BlindfoldedSurgery <team@blindfolded.surgery>"]
license = "MIT"
packages = [{ from = "src", include = "bot" }]

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.bjoernpetersen.net"
priority = "explicit"

[tool.poetry.dependencies]
azure-cognitiveservices-speech = "^1.28.0"
bs-config = { version = "1.0.2", extras = ["dotenv"], source = "internal" }
click = "^8.1.3"
prep-rate-limiter = { version = "5.0.4", extras = ["postgres"], source = "internal" }
python = "~3.12"
python-telegram-bot = "21.5"
sentry-sdk = "^2.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "~1.11"
pytest = "^8.0.0"
ruff = "0.6.3"
types-Deprecated = "^1.2.9"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "azure.*"
ignore_missing_imports = true

[tool.ruff.lint]
extend-select = [
    "I001",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
