---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bot
  serviceName: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        fsGroup: 500
      volumes:
        - name: scratch
          emptyDir:
            sizeLimit: "8Gi"
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: SCRATCH_DIR
              value: /scratch
          volumeMounts:
            - mountPath: /scratch
              name: scratch
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
