name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v2
    with:
      python-version: '3.12'

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v2
    with:
      python-version: '3.12'

  build-container-image:
    needs:
      - lint
      - test
    uses: BjoernPetersen/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: ubicloud-standard-2-arm
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: BjoernPetersen/actions-container/.github/workflows/clean.yml@v3
