on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: trazurebot-us
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
